import sys
import os
import yaml
from pathlib import Path

# Base ignores that are always applied
BASE_IGNORES = [
    ".git/",
    ".mission/",
    ".weaves/",
    ".idea/",
    ".vscode/",
    ".DS_Store",
    "compile_commands.json"
]

def load_config(repo_root):
    config_paths = [
        Path(repo_root) / ".weaves/weave.yaml",
        Path(repo_root) / ".mission/weave.yaml",
        Path(repo_root) / "weave.yaml",
    ]
    for path in config_paths:
        if path.exists():
            try:
                with open(path, 'r') as f:
                    return yaml.safe_load(f) or {}
            except Exception:
                pass
    return {}

def main():
    repo_root = Path(os.getcwd()).resolve()
    config = load_config(repo_root)
    
    # 1. Gather Ignores
    ignore_list = set(BASE_IGNORES)
    
    # Add user-defined ignores from weave.yaml
    if "ignores" in config:
        for item in config["ignores"]:
            ignore_list.add(item)

    # 2. Sort for stability
    sorted_ignores = sorted(list(ignore_list))
    
    # 3. Write .aiderignore
    ignore_file = repo_root / ".aiderignore"
    
    header = "# Auto-generated by Mission Control (sync_ignore)\n# Edit weave.yaml to change this list.\n"
    content = header + "\n".join(sorted_ignores) + "\n"
    
    # Only write if changed to preserve timestamp/avoid churn
    if ignore_file.exists():
        with open(ignore_file, 'r') as f:
            current_content = f.read()
        if current_content == content:
            # No change needed
            sys.exit(0)
            
    with open(ignore_file, 'w') as f:
        f.write(content)
    
    print(f"🤫 Synced .aiderignore ({len(sorted_ignores)} rules)")

if __name__ == "__main__":
    main()
