import sys
import os
import yaml
from pathlib import Path

# Safety: These must NEVER be ignored, or the toolchain breaks.
# We whitelist them to ensure they survive a "Nuclear" (*) ignore.
SYSTEM_WHITELIST = [
    "!.mission/",
    "!.weaves/",
    "!.git/",
    "!.aider*",
    "!compile_commands.json",
    "!weave.yaml"
]

def load_config(repo_root):
    config_paths = [
        Path(repo_root) / ".weaves/weave.yaml",
        Path(repo_root) / ".mission/weave.yaml",
        Path(repo_root) / "weave.yaml",
    ]
    for path in config_paths:
        if path.exists():
            try:
                with open(path, 'r') as f:
                    return yaml.safe_load(f) or {}
            except Exception:
                pass
    return {}

def main():
    repo_root = Path(os.getcwd()).resolve()
    config = load_config(repo_root)
    
    # 1. The Blocklist (User defined)
    # If you want "Nuclear", you put "*" in this list in weave.yaml
    ignore_lines = []
    if "ignores" in config:
        ignore_lines = config["ignores"]
    
    # 2. The Allowlist (Derived from Views + System)
    # We use a set to avoid duplicates
    whitelist_lines = set(SYSTEM_WHITELIST)
    
    if "views" in config:
        for view_name, patterns in config["views"].items():
            for pat in patterns:
                # Ensure it starts with '!' to act as an exception
                clean_pat = pat.strip()
                if not clean_pat.startswith("!"):
                    clean_pat = f"!{clean_pat}"
                whitelist_lines.add(clean_pat)
    
    # Add manual whitelist entries if they exist in config
    if "whitelist" in config:
        for pat in config["whitelist"]:
            clean_pat = pat.strip()
            if not clean_pat.startswith("!"):
                clean_pat = f"!{clean_pat}"
            whitelist_lines.add(clean_pat)

    # 3. Construct File Content
    # CRITICAL: Ignores must come FIRST. Whitelists must come LAST to override them.
    
    header = "# Auto-generated by Mission Control (sync_ignore)\n"
    header += "# strategy: Nuclear/Surgical mixed mode\n"
    
    content = header + "\n"
    
    # Write Blocks
    if ignore_lines:
        content += "# --- BLOCKS (ignores) ---\n"
        content += "\n".join(sorted(ignore_lines)) + "\n\n"
        
    # Write Allows
    content += "# --- ALLOWS (views + system) ---\n"
    content += "\n".join(sorted(list(whitelist_lines))) + "\n"

    # 4. Write (Idempotent)
    ignore_file = repo_root / ".aiderignore"
    
    if ignore_file.exists():
        with open(ignore_file, 'r') as f:
            current_content = f.read()
        if current_content == content:
            # No change needed
            sys.exit(0)
            
    with open(ignore_file, 'w') as f:
        f.write(content)
        
    print(f"☢️  Synced .aiderignore ({len(whitelist_lines)} allowed patterns)")

if __name__ == "__main__":
    main()
